corpsey/urls.py
from django.urls import include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.shortcuts import redirect
from . import views
from corpsey.apps.comics import views as comics_views
from corpsey.apps.comics import ajax as comics_ajax
from corpsey.apps.artists import views as artists_views
from django.contrib.auth import views as auth_views
from django import views as django_views
from django.contrib import admin
admin.autodiscover()
admin.site.site_header = 'Infinitely Corpsey'

urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^artists/$', artists_views.artists, name='artists'),
    re_path(r'^artist/([\d]+)/$', artists_views.entry, name='artist'),
    re_path(r'^about/$', views.about, name='about'),

    re_path(r'^catacombs/featured/$', comics_views.featured, name='featured'),
    re_path(r'^catacombs/uturn/(?P<uturn>[\d]+)/(?P<comic>\d+)/$', comics_views.uturn, name='comic-uturn'),
    re_path(r'^catacombs/uturn/(?P<uturn>[\d]+)/$', comics_views.uturn, name='comic-uturn-single'),
    re_path(r'^catacombs/(?P<comic_1>[\d]+)/(?P<comic_2>\d+)/$', comics_views.entry, name='comic-entry'),
    re_path(r'^catacombs/(?P<comic_1>[\d]+)/$', comics_views.entry, name='comic-entry-single'),
    re_path(r'^catacombs/$', lambda x: redirect('/')),
    re_path(r'^random/$', comics_views.random_comic, name='random-comic'),
    re_path(r'^enter_the_catacombs/$', comics_views.enter_the_catacombs, name='enter-the-catacombs'),
    re_path(r'^tree/$', comics_views.tree, name='tree'),
    re_path(r'^tree_css/$', comics_views.tree_css, name='tree-css'),
    re_path(r'^tree_circle/$', comics_views.tree_circle, name='tree-circle'),
    re_path(r'^tree_json/$', comics_views.tree_json, name='tree-json'),
    re_path(r'^artist_in_catacombs/(?P<artist>\d+)/(?P<num>\d+)/$', comics_views.artist_in_catacombs, name='artist-in-catacombs'),

    re_path(r'^contribute/upload/(?P<upload_code>[\w\-=_]+)/$', comics_views.contribute_upload, name='contribute-upload'),
    re_path(r'^contribute/upload/$', lambda x: redirect('/')),
    re_path(r'^contribute/$', comics_views.contribute, name='contribute'),
    re_path(r'^contribution_vote/$', comics_ajax.contribution_vote),
    re_path(r'^pad_panels/(?P<contribution>[\d]+)/$', comics_views.pad_panels, name='pad'),

    re_path(r'^contributions/$', comics_views.contributions, name='contributions'),
    re_path(r'^graveyard/$', comics_views.graveyard, name='graveyard'),

    re_path(r'^user/login/$', auth_views.LoginView.as_view(), name='user-login'),
    re_path(r'^user/logout/$', views.logout_view, name='user-logout'),
    re_path(r'^user/password/reset/$',
        auth_views.PasswordResetView.as_view(),
        {'post_reset_redirect' : '/user/password/reset/done/'},
        name='password_reset'),
    re_path(r'^user/password/reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done'),
    re_path(r'^user/password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        {'post_reset_redirect' : '/user/password/done/'},
        name='password_reset_confirm'),
    re_path(r'^user/password/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete'),

    # AJAX
    re_path(r'^ajax/get_comic_panels/$', comics_ajax.get_comic_panels),
    re_path(r'^ajax/get_uturn_panel/$', comics_ajax.get_uturn_panel),
    re_path(r'^ajax/get_nav_links/$', comics_ajax.get_nav_links),
    re_path(r'^ajax/get_new_leaf/$', comics_ajax.get_new_leaf),
    re_path(r'^ajax/load_more/$', comics_ajax.load_more),

    # Django and apps
    re_path(r'^admin/clearcache/', include('clearcache.urls')),
    re_path(r'^admin/', admin.site.urls),
    # re_path(r'^markitup/', markitup.urls),
    re_path(r'^media/(?P<path>.*)$', django_views.static.serve, {'document_root': settings.MEDIA_ROOT}),
]

corpsey/apps/artists/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from django.urls import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.cache import cache
import re

class Artist(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250, blank=True)
    first_name = models.CharField(max_length=250, blank=True)
    last_name = models.CharField(max_length=250, blank=True)
    email = models.CharField(max_length=250, blank=True)
    url = models.URLField(max_length=250, blank=True)
    image = ThumbnailerImageField(upload_to='artists', blank=True)
    num_comics = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def name_reversed(self):
        if self.last_name and self.first_name:
            return "%s, %s" % (self.last_name, self.first_name)
        else:
            return self.name

    def update_num_comics(self):
        self.num_comics = self.comics.count()
        self.save()

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('artist', args=[self.id])

    def save(self, *args, **kwargs):
        # generate first/last name from full name
        if self.name and not self.first_name and not self.last_name:
            foo = self.name.split(' ');
            self.last_name = foo[-1]
            self.first_name = re.sub(foo[-1], "",self.name).strip()
        super(Artist, self).save(*args, **kwargs)

@receiver(post_save, sender=Artist)
def clear_cache(sender, instance, created, **kwargs):
    """Clear artists page cache on artist save."""
    cache.delete('/artists/')

corpsey/apps/comics/models.py
from django.db import models
from corpsey.apps.artists.models import Artist
from easy_thumbnails.fields import ThumbnailerImageField
from mptt.models import MPTTModel, TreeForeignKey
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import datetime, timedelta
from django.conf import settings

from django.db.models.signals import post_save,pre_save
from django.dispatch import receiver
from django.core.cache import cache

from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global
saved_file.connect(generate_aliases_global)

class Comic(MPTTModel):
    id = models.AutoField(primary_key=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, null=True, blank=True, related_name='comics', on_delete=models.CASCADE)
    portal_to = models.ForeignKey('self', null=True, blank=True, related_name='portal', on_delete=models.CASCADE)
    notes = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    active = models.BooleanField(default=False)
    starter = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    full_image = ThumbnailerImageField(upload_to='comics', blank=True)
    panel1 = ThumbnailerImageField(upload_to='comics', blank=True)
    panel2 = ThumbnailerImageField(upload_to='comics', blank=True)
    panel3 = ThumbnailerImageField(upload_to='comics', blank=True)

    class Meta:
        ordering = ['tree_id', 'lft']

    def get_absolute_url(self):
        if self.parent:
            return reverse('comic-entry', kwargs={'comic_1': self.parent.id, 'comic_2': self.id})
        else:
            return reverse('comic-entry-single', kwargs={'comic_1': self.id})

    def __str__(self):
        return u"%s - %s" % (self.artist, self.date.strftime('%b %d \'%y'))

    def valid_to_follow(self):
        pending_contributions = len(Contribution.objects.filter(comic_id=self.id, pending=True))
        comic_children = len(self.get_children())
        return pending_contributions + comic_children < settings.MAX_COMIC_CHILDREN

    def prev_sib(self):
        """Root nodes infinite linkage, if first, link to last"""
        if self.is_root_node() and not self.get_previous_sibling(active=True):
            return Comic.objects.root_nodes().filter(active=True).reverse()[0]
        else:
            return self.get_previous_sibling(active=True)

    def next_sib(self):
        """Root nodes infinite linkage, if last, link to first"""
        if self.is_root_node() and not self.get_next_sibling(active=True):
            return Comic.objects.root_nodes().filter(active=True)[0]
        else:
            return self.get_next_sibling(active=True)

    def children(self):
        return self.get_children().filter(active=True)

    def get_uturn(self):
        return self.get_ancestors().all()[0].next_sib().uturn.all()

    def get_prev_comic_links(self):
        comic_links = []
        if self.is_child_node():
            comic_links.extend(self.get_ancestors(ascending=True).all()[:1])
        elif self.is_root_node() and self.prev_sib():
            comic_links.append(self.prev_sib())
        return comic_links

    def get_next_comic_links(self):
        comic_links = []
        if self.is_root_node():
            comic_links.append(self.next_sib())
        if self.children:
            comic_links.extend(self.children.all())
        if self.portal_to:
            comic_links.append(self.portal_to)

        return comic_links

@receiver(post_save, sender=Comic)
def clear_cache(sender, instance, created, **kwargs):
    """Clear homepage cache on comic save."""
    cache.delete('/')

@receiver(pre_save, sender=Comic)
def update_num_comics(sender, instance, **kwargs):
    """ Update num_comics for comic artists """
    old = Comic.objects.filter(pk=instance.pk)
    old = len(old) > 0 and old.get() or None
    if old:
        old.artist.num_comics = old.artist.num_comics - 1
        old.artist.save()
    instance.artist.num_comics = instance.artist.num_comics + 1
    instance.artist.save()

class Uturn(models.Model):
    id = models.AutoField(primary_key=True)
    portal_to = models.ForeignKey(Comic, related_name='uturn', on_delete=models.CASCADE)
    panel = ThumbnailerImageField(upload_to='comics', blank=True)

    def get_absolute_url(self):
        return reverse('corpsey.apps.comics.views.uturn', [str(self.id)])

    def __str__(self):
        return u"Uturn to %s" % (self.portal_to.artist)

class Contribution(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=250, blank=True)
    email = models.CharField(max_length=250, blank=True)
    website = models.URLField(max_length=250, blank=True)
    code = models.CharField(max_length=250, blank=True, help_text="Upload link is https://corpsey.trubble.club/contribute/upload/CODE_HERE/")
    date = models.DateTimeField(auto_now_add=True, blank=True)
    deadline = models.DateTimeField(blank=True)
    comic = models.ForeignKey(Comic, related_name='contributions', on_delete=models.CASCADE)
    panel1 = ThumbnailerImageField(upload_to='contributions', blank=True)
    panel2 = ThumbnailerImageField(upload_to='contributions', blank=True)
    panel3 = ThumbnailerImageField(upload_to='contributions', blank=True)
    pending = models.BooleanField(default=True)
    has_panels = models.BooleanField(default=False)
    accepted = models.BooleanField(default=False)
    notes = models.TextField(blank=True)

    # def admin_url(self):
    #     return reverse('admin:comics_contribution_change', args=[self.id])

    def votes_list(self):
        """List of votes for admin view"""
        votes_list = ''
        if self.votes:
            values = []
            for vote in self.votes.all():
                values.append(str(vote))
            votes_list = ', '.join(values)
        return votes_list

    def __str__(self):
        return u"Contribution from %s (following %s)" % (self.name, self.comic.artist)

class Rule(models.Model):
    id = models.AutoField(primary_key=True)
    text = models.TextField()
    def __str__(self):
        return u"%s" % self.text

class Vote(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    contribution = models.ForeignKey(Contribution, related_name='votes', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='votes', on_delete=models.CASCADE)
    approve = models.BooleanField(default=False)
    rule_broke = models.ForeignKey(Rule, null=True, blank=True, related_name='rules_broke', default=None, on_delete=models.CASCADE)
    notes = models.TextField(blank=True)

    def __str__(self):
        if self.approve:
            return u"Yea Vote for %s (by %s)" % (self.contribution, self.user.username)
        else:
            if self.rule_broke:
                return u"Nay Vote for %s : %s (by %s)" % (self.contribution, self.rule_broke,self.user.username)
            else:
                return u"Nay Vote for %s : %s (by %s)" % (self.contribution, self.notes, self.user.username)

corpsey/apps/comics/forms.py
from django import forms

class UploadForm(forms.Form):
    comic_panels = forms.FileField(widget=forms.ClearableFileInput(), required=False)
    name = forms.CharField(label='Your name', widget=forms.TextInput(attrs={'placeholder': 'Corpsey Infinitus'}))
    email = forms.CharField(label='Your email', widget=forms.TextInput(attrs={'placeholder': 'corpsey@aol.com'}))
    website = forms.CharField(label='Your website', required=False, widget=forms.TextInput(attrs={'placeholder': 'corpsey.trubble.club'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["comic_panels"].widget.attrs.update({"multiple": "true"})

class ContributeForm(forms.Form):
    name = forms.CharField(label='Your name', widget=forms.TextInput(attrs={'placeholder': 'Corpsey Infinitus', 'class': 'required'}))
    email = forms.EmailField(label='Your email', widget=forms.TextInput(attrs={'placeholder': 'corpsey@aol.com', 'class': 'email required'}))
    comic_id = forms.CharField()

corpsey/apps/artists/views.py
from corpsey.apps.artists.models import *
from corpsey.apps.comics.models import *
from django.http import JsonResponse
from django.views.decorators.cache import cache_page
from django.contrib.flatpages.models import FlatPage
from django.shortcuts import render

def entry(request, artist_id):
    pass

@cache_page(60 * 15)
def artists(request):
    q = request.GET.get('term', '')
    if q:
        artist_set = Artist.objects.exclude(comics=None).filter(name__icontains = q )
    else:
        artist_set = Artist.objects.exclude(comics=None).order_by('last_name')
    page = FlatPage.objects.get(url='/artists/')
    return render(request, 'artists.html',  {
        'title': page.title,
        'page': page,
        'q': q,
        'artist_set': artist_set,
        })

def get_artists(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        artists = Artist.objects.exclude(comics=None).filter(name__icontains = q )[:20]
        results = []
        for artist in artists:
            url = ''
            comics = Comic.objects.filter(artist_id = artist.id)
            if len(comics) > 0:
                url = comics[0].get_absolute_url()
            artist_json = {}
            artist_json['id'] = artist.id
            artist_json['label'] = artist.name
            artist_json['url'] = url
            artist_json['value'] = artist.name
            results.append(artist_json)

            # artist_json['comics'] = []
            # if artist.num_comics > 1:
            #   for comic in artist.comics.all()[1:]:
            #     artist_json['comic_urls']
            #   endfor
            # endif

        data = results
    else:
        data = 'fail'
    return JsonResponse(data, safe=False)

corpsey/views.py
from corpsey.apps.comics.models import *
from corpsey.apps.artists.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.flatpages.models import FlatPage
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.template import RequestContext
from django.views.decorators.cache import cache_page
from math import ceil

@login_required()
def logout_view(request):
    """Custom logout with redirect."""
    logout(request)
    return redirect('/?logged_out_ok=1')

@cache_page(60 * 15)
def home(request):
    comic_set = Comic.objects.filter(active=True).order_by('-date')[:10]
    page = FlatPage.objects.get(url='/')
    num_artists = Artist.objects.exclude(comics=None).count()
    total_pages = ceil(Comic.objects.count() / 10)
    return render(request, 'home.html',  {
        'title': '',
        'page': page,
        'total_pages': total_pages,
        'num_artists': num_artists,
        'comic_set': comic_set,
        })

@cache_page(60 * 15)
def about(request):
    page = FlatPage.objects.get(url='/about/')
    return render(request, 'about.html',  {
        'title': page.title,
        'page': page,
        })

corpsey/templates/comics/contribute.html
{% extends "base.html" %}
{% load thumbnail humanize static %}
{% load honeypot %}

{% block body_id %}contribute-page{% endblock %}
{% block title %}Contribute!{% endblock %}

{% block content %}

{% if message %}
  <div class="notice"><p>{{ message }}</p></div>
{% endif %}

{% if step == 1 %}
<section id="step1" class="step active">
    <div class="user-content">
        <h1>{{ page.title|safe }}</h1>
        {{ page.content|safe }}
    </div>

    <form class="contribute" action="{% url 'contribute' %}" method="post">
        <h2>Your parent strip:</h2>
        <div id="parent_comic">
            {% include "comics/strip.html" with comic=parent_comic %}
        </div>
        <p><a class="new-leaf refresh" href="#">Give me another random strip to follow</a></p>

        <fieldset class="info">
            <label for="id_name" class="required">{{ contribute_form.name.label_tag }}</label>
            {{ contribute_form.name }}
            {% if contribute_form.name.errors %}
                <div class="field-error">{{ contribute_form.name.errors }}</div>
            {% endif %}

            <label for="id_email" class="required">{{ contribute_form.email.label_tag }}</label>
            {{ contribute_form.email }}
            {% if contribute_form.email.errors %}
                <div class="field-error">{{ contribute_form.email.errors }}</div>
            {% endif %}

            <div class="hidden">{{ contribute_form.comic_id }}</div>
            {% csrf_token %}
            {% render_honeypot_field %}
        </fieldset>

        <div class="actions">
            <button class="button" type="submit">Yes! I'd like to reserve my spot after this strip!</button>
            <p class="note">Remember! You have 7 days to submit your follow up panels ({{ deadline|date:'l, M j' }}). You can only reserve one spot at a time.</p>
        </div>
    </form>
</section>
{% else %}
<section id="step2" class="step {% if step == 2 %}active{% endif %}">
    <div class="user-content">
        <h1>{{ page2.title|safe }}</h1>
        {{ page2.content|safe }}
    </div>
</section>
{% endif %}
{% endblock content %}

{% block extra_javascript %}
<script src="{% static "js/contribute-min.js" %}" type="text/javascript"></script>
{% endblock extra_javascript %}
{% block icanhaz_templates %}
    {% include "js/comic_single.html" %}
{% endblock icanhaz_templates %}

corpsey/templates/comics/contribute_upload.html
{% extends "base.html" %}
{% load thumbnail static %}

{% block body_id %}contribute-page{% endblock %}
{% block title %}Contribute to The Infinite Corpse!{% endblock %}

{% block content %}

    {% if message %}
        <div class="notice"><p>{{ message|safe }}</p></div>
    {% endif %}

    {% if form %}
    <section id="contribute-form" class="step {% if not contribution.has_panels %}active{% endif %}">
        <div class="user-content">
            <h1>{{ page.title|safe }}</h1>
            {{ page.content|safe }}
        </div>

        <h2>Your parent strip:</h2>
        <div id="parent_comic">
            {% include "comics/strip.html" with comic=parent_comic %}
        </div>

        <form id="contribute" class="contribute" action="{% url 'contribute-upload' upload_code %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.non_field_errors }}
                  <div class="dropzone">
                    <div class="dz-previews"></div>
                    <div class="dz-default dz-message"><span class="no-touch">Drag images here or </span><a class="button dz-clickable">Select images to upload</a></div>
                    <div class="dz-drag-message">Drag images to reorder.</div>
                    <div class="fallback">{{ form.comic_panels }}</div>
                  </div>
                  {% if form.comic_panels.errors %}
                     <div class="field-error">{{ form.comic_panels.errors }}</div>
                  {% endif %}
                <fieldset class="info">
                    <label for="id_name" class="required">{{ form.name.label_tag }}</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                       <div class="field-error">{{ form.name.errors }}</div>
                    {% endif %}

                    <label for="id_email" class="required">{{ form.email.label_tag }}</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                       <div class="field-error">{{ form.email.errors }}</div>
                    {% endif %}

                    <label for="id_website">{{ form.website.label_tag }}</label>
                    {{ form.website }}
                  {% if form.website.errors %}
                     <div class="field-error">{{ form.website.errors }}</div>
                  {% endif %}
                </fieldset>
                {{ form.parent_id.as_hidden }}

            <div class="actions">
              <button class="button" type="submit">Upload!</button>
            </div>
        </form>
    </section>

    <section id="contribute-ok" class="step {% if contribution.has_panels %}active{% endif %}">
        <div class="user-content">
            <h1>{{ page2.title|safe }}</h1>
            {{ page2.content|safe }}
        </div>
    </section>
    {% endif %}
{% endblock content %}

{% block extra_javascript %}
<script src="{% static "js/contribute-min.js" %}" type="text/javascript"></script>
{% endblock extra_javascript %}

{% block icanhaz_templates %}
    {% include "js/comic_single.html" %}
{% endblock icanhaz_templates %}

corpsey/templates/comics/contribution.html
{% load thumbnail %}

{% if contribution.panel1 %}
<div class="queue" data-contribution-id="{{ contribution.id }}" id="contribution-{{ contribution.id }}">
	<article class="comic" data-comic-id="{{ comic.id }}">
	  <h1>Following {{ comic.artist.name }}</h1>
	  <a target="_blank" href="{{ comic.get_absolute_url }}">{% if comic.panel1 %}<img class="panel" src="{{ comic.panel1.midsize.url }}">{% endif %}{% if comic.panel2 %}<img class="panel" src="{{ comic.panel2.midsize.url }}">{% endif %}{% if comic.panel3 %}<img class="panel" src="{{ comic.panel3.midsize.url }}">{% endif %}</a>
	  </ul>
	</article>

	<article class="contribution" data-contribution-id="{{ contribution.id }}">
	  <h1>Contribution from: {% if contribution.website %}<a target="_blank" href="{{ contribution.website }}">{{ contribution.name }}</a>{% else %}{{ contribution.name }}{% endif %} &lt;{{ contribution.email }}&gt;</h1>
	  <ul>
	    <li>{% if contribution.panel1 %}<img class="panel" src="{{ contribution.panel1.midsize.url }}" srcset="{{ contribution.panel1.midsize.url }} 1x, {{ contribution.panel1.midsize_hd.url }} 2x">{% else %}No image for panel 1{% endif %}</li>
	    <li>{% if contribution.panel2 %}<img class="panel" src="{{ contribution.panel2.midsize.url }}" srcset="{{ contribution.panel2.midsize.url }} 1x, {{ contribution.panel2.midsize_hd.url }} 2x">{% else %}No image for panel 2{% endif %}</li>
	    <li>{% if contribution.panel3 %}<img class="panel" src="{{ contribution.panel3.midsize.url }}" srcset="{{ contribution.panel3.midsize.url }} 1x, {{ contribution.panel3.midsize_hd.url }} 2x">{% else %}No image for panel 3{% endif %}</li>
	  </ul>
	</article>

	{% if contribution.votes.all %}
		<h2>Votes so far:</h2>
		<ul class="votes">
		{% for vote in contribution.votes.all %}
			{% if vote.approve %}
				<li>Yea vote</li>
			{% else %}
				<li>Nay vote: <em>{{ vote.notes }}</em></li>
			{% endif %}
		{% endfor %}
		</ul>
	{% endif %}

	{% if user.username == 'nate' or user.username == 'aaron' %}
		<p><a onclick="return confirm('Are you sure? This alters the original images and adds 20px of white padding.')" target="_blank" href="/pad_panels/{{ contribution.id }}/">Add Padding to Panels</a></p>
	{% endif %}

	<div class="actions">
		<a class="button yea" href="/contributions/vote/{{ contribution.id }}/1/">Yea</a>
		<a class="button nay" href="/contributions/vote/{{ contribution.id }}/0/">Nay</a>
	</div>
</div>
{% endif %}

corpsey/templates/comics/contributions.html
{% extends "base.html" %}
{% load thumbnail static %}

{% block body_id %}contributions{% endblock %}
{% block title %}Pending Contributions{% endblock %}

{% block content %}
  <h1>Pending Contributions</h1>
  <p style="margin:-15px 0 20px">Signed in as {{ user.username }}. <a class="button" href="{% url 'user-logout' %}">Log Out</a></p>
  {% for contribution in contributions %}
    {% include "comics/contribution.html" with contribution=contribution comic=contribution.comic %}
  {% empty %}
  	<p>No pending contributions found that you haven't voted on. They may have already been approved or rejected.</p>
  {% endfor %}
  <div id="rules">
    <h2>For reference, these are the seven rules:</h2>
  	<ul>
      <li>The actions within the panels must be clear, and easy to read.</li>
      <li>Three perfectly square panels which directly follow the previous artist's panels, in your own style, in your own palette. Draw Corpsey how you would draw him, not necessarily how the artist before you did. Black and white or color are both encouraged. We'd love it to be a wonderful patchwork of all sorts of things, but no halftones please.</li>
      <li>The main character Corpsey must always be in the comic. He is already dead, so you cannot kill him. Your panels cannot be the end of the comic.</li>
      <li>Keep it PG-13.</li>
      <li>Panels must be RGB, at least 1200x1200 pixels, and saved as JPGs.</li>
      <li>Please DO NOT include characters from your own comics, or others already created. We want this to be 100% original.</li>
  	</ul>
      <p class="note">Write one or two sentences about what could make their piece better. Try to put yourself into their shoes, and try not to be mean. These notes are compiled and included in the rejection email if Nayed.</p>
      <textarea id="notes"></textarea>
      <p><a class="button rule other">Submit NAY Vote</a></p>

  </div>
{% endblock content %}

{% block extra_javascript %}
  <script src="{% static "js/contributions.js" %}" type="text/javascript"></script>
{% endblock extra_javascript %}

corpsey/templates/comics/listing_block.html
{% if extra_divider != None %}
    <div class="bone-divider even"></div>
{% endif %}
{% for comic in comic_set %}
    {% include "comics/listing.html" %}
    {% if not forloop.last %}
        <div class="bone-divider {% cycle 'odd' 'even' %}"></div>
    {% endif %}
{% endfor %}

corpsey/templates/comics/next_comic_links.html
<nav class="next comic-nav">
  <h3>Next</h3>
  <ul class="next-comic">
    {% for comic in comic_links %}
      <li><a title="{{ root_comic.artist.name }} / {{ comic.artist.name }}" data-comic-id="{{ comic.id }}" class="next button" href="/catacombs/{{ root_comic.id }}/{{ comic.id }}/">{{ comic.artist.first_name }} <br>{{ comic.artist.last_name }}</a></li>
    {% endfor %}
    {% for uturn in uturn %}
      <li><a title="Trubble Club / {{ root_comic.artist.name }}" data-uturn-id="{{ uturn.id }}" class="next button" href="/catacombs/uturn/{{ uturn.id }}/{{ root_comic.id }}/">Trubble <br>Club</a></li>
    {% endfor %}
  </ul>
</nav>